@startuml
left to right direction
actor ユーザー

package 利用者 {
  usecase "利用者の一覧を見る"
  usecase "利用者の削除"
  usecase "利用者の更新"
  usecase "利用者情報を入力"
  usecase "利用者の登録"
  usecase "利用者情報のキーワード検索"
  usecase "利用者情報の詳細検索" 
  usecase "利用者を選択"
  利用者の一覧を見る --|> 利用者の登録
  利用者の登録 --|> 利用者情報を入力
  利用者の一覧を見る --|> 利用者を選択
  利用者を選択 --|> 利用者の更新
  利用者の更新 --|> 利用者情報を入力
  利用者を選択 --|> 利用者の削除
  利用者の一覧を見る --|> 利用者情報のキーワード検索
  利用者の一覧を見る --|> 利用者情報の詳細検索
}
ユーザー --> 利用者の一覧を見る

package 食事 {
  usecase "食事の一覧を見る"
  usecase "食事の削除"
  usecase "食事の更新"
  usecase "食事情報を入力"
  usecase "食事の登録"
  usecase "食事情報のキーワード検索"
  usecase "食事情報の詳細検索" 
  usecase "食事を選択"
  食事の一覧を見る --|> 食事の登録
  食事の登録 --|> 食事情報を入力
  食事の一覧を見る --|> 食事を選択
  食事を選択 --|> 食事の更新
  食事の更新 --|> 食事情報を入力
  食事を選択 --|> 食事の削除
  食事の一覧を見る --|> 食事情報のキーワード検索
  食事の一覧を見る --|> 食事情報の詳細検索
}
ユーザー --> 食事の一覧を見る

package 排泄 {
  usecase "排泄の一覧を見る"
  usecase "排泄の削除"
  usecase "排泄の更新"
  usecase "排泄情報を入力"
  usecase "排泄の登録"
  usecase "排泄情報のキーワード検索"
  usecase "排泄情報の詳細検索" 
  usecase "排泄を選択"
  排泄の一覧を見る --|> 排泄の登録
  排泄の登録 --|> 排泄情報を入力
  排泄の一覧を見る --|> 排泄を選択
  排泄を選択 --|> 排泄の更新
  排泄の更新 --|> 排泄情報を入力
  排泄を選択 --|> 排泄の削除
  排泄の一覧を見る --|> 排泄情報のキーワード検索
  排泄の一覧を見る --|> 排泄情報の詳細検索
}
ユーザー --> 排泄の一覧を見る

package 睡眠 {
  usecase "睡眠の一覧を見る"
  usecase "睡眠の削除"
  usecase "睡眠の更新"
  usecase "睡眠情報を入力"
  usecase "睡眠の登録"
  usecase "睡眠情報のキーワード検索"
  usecase "睡眠情報の詳細検索" 
  usecase "睡眠を選択"
  睡眠の一覧を見る --|> 睡眠の登録
  睡眠の登録 --|> 睡眠情報を入力
  睡眠の一覧を見る --|> 睡眠を選択
  睡眠を選択 --|> 睡眠の更新
  睡眠の更新 --|> 睡眠情報を入力
  睡眠を選択 --|> 睡眠の削除
  睡眠の一覧を見る --|> 睡眠情報のキーワード検索
  睡眠の一覧を見る --|> 睡眠情報の詳細検索
}
ユーザー --> 睡眠の一覧を見る

package 臨時薬 {
  usecase "臨時薬の一覧を見る"
  usecase "臨時薬の削除"
  usecase "臨時薬の更新"
  usecase "臨時薬情報を入力"
  usecase "臨時薬の登録"
  usecase "臨時薬情報のキーワード検索"
  usecase "臨時薬情報の詳細検索" 
  usecase "臨時薬を選択"
  臨時薬の一覧を見る --|> 臨時薬の登録
  臨時薬の登録 --|> 臨時薬情報を入力
  臨時薬の一覧を見る --|> 臨時薬を選択
  臨時薬を選択 --|> 臨時薬の更新
  臨時薬の更新 --|> 臨時薬情報を入力
  臨時薬を選択 --|> 臨時薬の削除
  臨時薬の一覧を見る --|> 臨時薬情報のキーワード検索
  臨時薬の一覧を見る --|> 臨時薬情報の詳細検索
}
ユーザー --> 臨時薬の一覧を見る

package バイタルサイン {
  usecase "バイタルサインの一覧を見る"
  usecase "バイタルサインの削除"
  usecase "バイタルサインの更新"
  usecase "バイタルサイン情報を入力"
  usecase "バイタルサインの登録"
  usecase "バイタルサイン情報のキーワード検索"
  usecase "バイタルサイン情報の詳細検索" 
  usecase "バイタルサインを選択"
  バイタルサインの一覧を見る --|> バイタルサインの登録
  バイタルサインの登録 --|> バイタルサイン情報を入力
  バイタルサインの一覧を見る --|> バイタルサインを選択
  バイタルサインを選択 --|> バイタルサインの更新
  バイタルサインの更新 --|> バイタルサイン情報を入力
  バイタルサインを選択 --|> バイタルサインの削除
  バイタルサインの一覧を見る --|> バイタルサイン情報のキーワード検索
  バイタルサインの一覧を見る --|> バイタルサイン情報の詳細検索
}
ユーザー --> バイタルサインの一覧を見る

package 入浴 {
  usecase "入浴の一覧を見る"
  usecase "入浴の削除"
  usecase "入浴の更新"
  usecase "入浴情報を入力"
  usecase "入浴の登録"
  usecase "入浴情報のキーワード検索"
  usecase "入浴情報の詳細検索" 
  usecase "入浴を選択"
  入浴の一覧を見る --|> 入浴の登録
  入浴の登録 --|> 入浴情報を入力
  入浴の一覧を見る --|> 入浴を選択
  入浴を選択 --|> 入浴の更新
  入浴の更新 --|> 入浴情報を入力
  入浴を選択 --|> 入浴の削除
  入浴の一覧を見る --|> 入浴情報のキーワード検索
  入浴の一覧を見る --|> 入浴情報の詳細検索
}
ユーザー --> 入浴の一覧を見る

package アクシデント {
  usecase "アクシデントの一覧を見る"
  usecase "アクシデントの削除"
  usecase "アクシデントの更新"
  usecase "アクシデント情報を入力"
  usecase "アクシデントの登録"
  usecase "アクシデント情報のキーワード検索"
  usecase "アクシデント情報の詳細検索" 
  usecase "アクシデントを選択"
  アクシデントの一覧を見る --|> アクシデントの登録
  アクシデントの登録 --|> アクシデント情報を入力
  アクシデントの一覧を見る --|> アクシデントを選択
  アクシデントを選択 --|> アクシデントの更新
  アクシデントの更新 --|> アクシデント情報を入力
  アクシデントを選択 --|> アクシデントの削除
  アクシデントの一覧を見る --|> アクシデント情報のキーワード検索
  アクシデントの一覧を見る --|> アクシデント情報の詳細検索
}
ユーザー --> アクシデントの一覧を見る

package 入浴予定 {
  usecase "入浴予定の一覧を見る"
  usecase "入浴予定の削除"
  usecase "入浴予定の更新"
  usecase "入浴予定情報を入力"
  usecase "入浴予定の登録"
  usecase "入浴予定情報のキーワード検索"
  usecase "入浴予定情報の詳細検索" 
  usecase "入浴予定を選択"
  入浴予定の一覧を見る --|> 入浴予定の登録
  入浴予定の登録 --|> 入浴予定情報を入力
  入浴予定の一覧を見る --|> 入浴予定を選択
  入浴予定を選択 --|> 入浴予定の更新
  入浴予定の更新 --|> 入浴予定情報を入力
  入浴予定を選択 --|> 入浴予定の削除
  入浴予定の一覧を見る --|> 入浴予定情報のキーワード検索
  入浴予定の一覧を見る --|> 入浴予定情報の詳細検索
}
ユーザー --> 入浴予定の一覧を見る

package 入浴予定一括登録 {
  usecase 入浴予定のダウンロード
  usecase 入浴予定の一括登録
  usecase 入浴予定一括履歴の一覧を見る
}
ユーザー --> 入浴予定のダウンロード 
ユーザー --> 入浴予定の一括登録
ユーザー --> 入浴予定一括履歴の一覧を見る

@enduml